name: Comment Reaction

on:
  issue_comment:
    types: [created]

jobs:
  add_reaction:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains trigger phrase
        id: check-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const triggerPhrases = ['hello']; // لیست عبارات مورد نظر برای شناسایی کامنت‌ها
            const comment = context.payload.comment.body.toLowerCase();
            const containsTrigger = triggerPhrases.some(phrase => comment.includes(phrase));
            return { containsTrigger };

      - name: Add reaction if trigger phrase found
        if: steps.check-comment.outputs.containsTrigger == true
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reaction = 'heart'; // نوع ری‌اکشن مورد نظرتان
            await octokit.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: reaction,
              console.log(reaction)
            });
