name: create-comment

on:
    push


jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
          - name: Add reactions
            uses: peter-evans/create-or-update-comment@v3
            with:
                comment-id: 1692127283
                reactions: +1  
